### ISSUE TITLE
Entering comments twice to one page does not give save button

### ISSUE THREAD

**Issue by reactor0138** [leorenis/icontent#10]
Ok so make a comment on a page and save it. Then the option to add a new comment is immediately there but there is no save button so if you have typed the next comment immediately instead of editing the one you just added there is no way to save the comment as the save button has disappeared. So the saving of the first comment is not fully refreshing the screen. 

Work round: 
if you refresh the page after making the first comment then the save button appears on the screen for the next comment.

**Comment by drachels** [comment]
Not sure when, or in which version this was fixed, but the Save button is there and available for any combination of Private or Feature checked/not checked.
