### ISSUE TITLE
Update for Moodl 3.2.

### ISSUE THREAD

**Issue by trhp** [leorenis/icontent#14]
This is indeed a great plugin - thanks so much.
It would be great if the plugin was updated for moodle 3.2.
Do you have any plans doing that?
Would really appreciate it.

**Comment by leorenis** [comment]
Hey, thanks for use this plugin. Today I released the new version (1.0.6). It's compatible with moodle 3.8 and I've fixed up a lot of troubles. If possible, please check again and tell me if the problem persists.
