### ISSUE TITLE
Weird visualization of content

### ISSUE THREAD

**Issue by aerosmesh** [leorenis/icontent#21]
When you start to navigate through differente pages, the page container moves to left, and using only a small part of available space. The bottom navigation buttons it ups and use the right part of the available space.

I attached a image of this issue for better explanation.

Thanks in advance!!!

Moodle version: 3.4
Theme version: Adaptable 1.6.1
Icontent version: 1.0.5

![bootstrap](https://user-images.githubusercontent.com/19270262/37495250-950ef22a-2869-11e8-8090-a090e46be460.jpg)

**Comment by duanchenggui** [comment]
I came across the same problem, and attach the following screen shot for your reference.
Moodle version: 3.4
Theme version: Clean (and Essential)
Icontent version: 1.0.5
![1](https://user-images.githubusercontent.com/3714609/37636054-80760996-2c3a-11e8-8c08-47eb592e4592.png)

**Comment by duanchenggui** [comment]
Some other minor issues, as attached.
thanks
![2](https://user-images.githubusercontent.com/3714609/37636235-db52a7ba-2c3b-11e8-883e-84521f763dfe.png)

**Comment by hvanatoa** [comment]
Same problem here:
Moodle version: 3.5
Theme version: Adaptable 1.7
Icontent version: 1.0.4

![image](https://user-images.githubusercontent.com/41390499/42900935-e017569c-8ad2-11e8-80da-e7f57c31119d.png)

**Comment by leorenis** [comment]
Hey,
This problem has been fixed up in a new version of the plugin (1.0.6 Moodle 3.8).
Best regards.
