### ISSUE TITLE
iContent navigatiemenu doesn’t work properly in Moodle version 3.5

### ISSUE THREAD

**Issue by pietervorstenbosch** [leorenis/icontent#23]
After one or two clicks in the menu the next content is not displayed anymore.
In the example I clicked once on page 1 then 2 then 3. On the click on 3 the page doesn't show.

When I reload the page in the browser I can click on 3 and it will show me the page but the next click there is again a no-show.

<img width="1277" alt="schermafbeelding 2018-08-23 om 19 35 43" src="https://user-images.githubusercontent.com/27893690/44541947-d3852f80-a70b-11e8-9752-3b32088acff1.png">

Moodle 3.5
Theme essential
Content pages version 2016091500

**Comment by leorenis** [comment]
Hey, Thanks for this issue.
This issue has been fixed up in the recent version.
Best regards.
