### ISSUE TITLE
Lack of access check in ajax.php

### ISSUE THREAD

**Issue by mudrd8mz** [leorenis/icontent#4]
In ajax.php there is 

```
$allowedit  = has_capability('mod/icontent:edit', $context);
```

but then I can't see that the capability would be actually checked. As I can see, actions can be performed by any users and are saved to the database. That looks like a serious bug.

**Comment by leorenis** [comment]
Dear David, thank you for highlighting this BUG. Really there was a distraction in this part of the code. Added the require_capability () function for all actions.

**Comment by leorenis** [comment]
Dear David, 
Thank you for highlighting this BUG. Really there was a distraction in this part of the code. Added the require_capability () function for all actions.
Update successfully accomplished!
Regards.
