### ISSUE TITLE
Erro ao adicionar nova questão a partir de outra

### ISSUE THREAD

**Issue by AndreaOliveira** [leorenis/icontent#7]
Fui adicionar uma nova **questão** na atividade e apareceu o seguinte erro;
'Erro ao gravar na base de dados'

SELECT q.id, q.qtype, q.name, q.timecreated, q.timemodified, q.createdby, q.modifiedby, c.contextid 
FROM mdl_question q 
JOIN mdl_question_categories c 
ON c.id = q.category 
WHERE c.contextid = '1568' 
AND q.qtype IN (N'essay',N'match',N'multichoice',N'truefalse') 
ORDER BY q.name ASC LIMIT 20 OFFSET 0
[array (
0 => 1568,
1 => 'essay',
2 => 'match',
3 => 'multichoice',
4 => 'truefalse',
)] 
Error code: dmlreadexception

---

Stack trace:
line 474 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 859 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 907 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 556 of \mod\icontent\locallib.php: call to sqlsrv_native_moodle_database->get_records_sql()
line 85 of \mod\icontent\addquestionpage.php: call to icontent_get_questions_of_questionbank(

**Comment by leorenis** [comment]
Olá Andreia,
Atualização realizada com sucesso! 
Peço por favor que atualize novamente o arquivo locallib.php
Muito obrigado!

**Comment by AndreaOliveira** [comment]
Eu atualizei, esse erro foi consertado e, apareceu o outro erro após a escolha da questão.
Segue:

Stack trace:
line 474 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 859 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 907 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 1527 of \lib\dml\moodle_database.php: call to sqlsrv_native_moodle_database->get_records_sql()
line 998 of \mod\icontent\locallib.php: call to moodle_database->get_record_sql()
line 1713 of \mod\icontent\locallib.php: call to icontent_get_attempt_summary_by_page()
line 2354 of \mod\icontent\locallib.php: call to icontent_make_questionsarea()
line 88 of \mod\icontent\view.php: call to icontent_get_fullpageicontent()

**Comment by leorenis** [comment]
Correção realizada com sucesso!

**Comment by AndreaOliveira** [comment]
Obrigada Léo!!!
